In [49]:
from topagnps2cche1d.tools import find_extremities_binary
from scipy.signal import convolve2d
import numpy as np

In [84]:
def get_neighborhood(I, r, c):
    neighborhood = np.array(
        [
            [
                I[r - 1, c - 1] if (r - 1 >= 0) and (c - 1 >= 0) else 0,
                I[r - 1, c] if r - 1 >= 0 else 0,
                I[r - 1, c + 1] if (r - 1 >= 0) and (c + 1 <= I.shape[1]) else 0,
            ],
            [
                I[r, c - 1] if (c - 1 > 0) else 0,
                I[r, c],
                I[r, c + 1] if (c + 1 <= I.shape[1] - 1) else 0,
            ],
            [
                I[r + 1, c - 1] if (r + 1 <= I.shape[0] - 1) and (c - 1 >= 0) else 0,
                I[r + 1, c] if r + 1 <= I.shape[0] - 1 else 0,
                I[r + 1, c + 1]
                if (r + 1 <= I.shape[0] - 1) and (c + 1 <= I.shape[1])
                else 0,
            ],
        ]
    )
    return neighborhood


def find_extremities_binary(img, output_index_starts_one=False):
    (rows, cols) = np.nonzero(img)

    # Initialize empty list of coordinates
    extremities = []

    # A MEDITER.................
    # For each non-zero pixel...
    for r, c in zip(rows, cols):
        neighborhood = get_neighborhood(img, r, c)
        if neighborhood == np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]]):
            extremities.append((r, c))
            break
        elif neighborhood == np.array([[1, 1, 0], [0, 1, 0], [0, 0, 0]]):
            extremities.append((r - 1, c - 1))

        elif neighborhood == np.array([[0, 1, 1], [0, 1, 0], [0, 0, 0]]):
            extremities.append((r - 1, c + 1))

        elif neighborhood == np.array([[0, 0, 0], [0, 1, 0], [0, 1, 0]]):
            extremities.append((r + 1, c))

        elif neighborhood == np.array([[0, 0, 0], [1, 1, 0], [0, 0, 0]]):
            extremities.append((r, c - 1))

        elif neighborhood == np.array([[1, 0, 0], [0, 1, 0], [0, 0, 0]]):
            extremities.append((r - 1, c - 1))

    if output_index_starts_one:
        extremities = [(r + 1, c + 1) for r, c in extremities]

    return extremities

In [109]:
I = np.array([[0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [1, 1, 0, 0]])

# I = np.array([[0,1,0,0],
#               [0,1,0,0],
#               [0,1,0,0],
#               [0,1,0,0]])

# I = np.array([[0,1,0,0],
#               [0,1,0,0],
#               [0,1,1,0],
#               [0,0,1,0]])

# I = np.array([[0,1,0],
#               [0,1,0],
#               [1,1,0]])

neighb0 = np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]])

neighb1 = np.array([[0, 1, 0], [0, 1, 0], [0, 0, 0]])

neighb1 = np.array([[0, 0, 1], [0, 1, 0], [0, 0, 0]])

neighborhoods = {0: np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]]), 1: []}


neighbor_mask = np.array([[1, 1, 1], [1, 0, 1], [1, 1, 1]])

J = convolve2d(I, neighbor_mask, mode="same", boundary="fill", fillvalue=0)
J = np.where(I == 0, 0, J)
print(J)

extremities = [
    (r, c) for r, c in np.transpose(np.where((J <= min(2, J[J > 0].min())) & (I == 1)))
]
print(extremities)

[[0 1 0 0]
 [0 2 0 0]
 [0 3 0 0]
 [2 2 0 0]]
[(0, 1)]


In [139]:
I = np.array([[0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [1, 1, 0, 0]])

print(I.shape)

print(get_neighborhood(I, 3, 0))

(4, 4)
[[0 0 1]
 [0 1 1]
 [0 0 0]]


In [132]:
I[0, 1]

1

In [108]:
np.rot90(I, 4)

array([[0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 1, 0, 0]])

In [94]:
rows, cols = np.where((J <= 2) & (I == 1))

for r, c in zip(rows, cols):
    print(r, c)

0 1
3 2


In [86]:
extremities = find_extremities_binary(I)
print(extremities)

[[0 1]]
